all:
	make -C garray
	make -C gstack
	make -C gcomplex
	make -C gpoint
clean:
	make -C garray clean
	make -C gstack clean
	make -C gstack clean
	make -C gstack clean
test:
	make -C garray test
	make -C gstack test
	make -C gstack test
	make -C gstack test
