all:
	make -C account
	make -C box
	make -C point
	make -C customer
	make -C color
	make -C ipaddr
clean:
	make -C account clean
	make -C box clean
	make -C point clean
	make -C customer clean
	make -C color clean
	make -C ipaddr clean
test:
	make -C account test
	make -C box test
	make -C point test
	make -C customer test
	make -C color test
	make -C ipaddr test

