all:
	make -C banking
	make -C billing
	make -C employees
	make -C shapes
clean:
	make -C banking clean
	make -C billing clean
	make -C employees clean
	make -C shapes clean
clean:
	make -C banking test
	make -C billing test
	make -C employees test
	make -C shapes test
