all:
	make -C complex
	make -C mytime
	make -C distance
	make -C fraction
	make -C mytime
clean:
	make -C complex clean
	make -C mytime clean
	make -C distance clean
	make -C fraction clean
	make -C mytime clean
test:
	make -C complex test
	make -C mytime test
	make -C distance test
	make -C fraction test
	make -C mytime test

